# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ADMIN: MEMBER
        BACK: [MEMBER, ADMIN]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # back
        api_user:
           id: app.security.user.provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:   ^(/back/login)$
            anonymous: ~

        login:
            pattern:  ^/(back/login-check)
            security: false

        back_secured_area:
            pattern: ^/back
            context: user
            provider: api_user
            logout:
                path: /back/logout
                target: /back/login
            simple-form:
                login_path: /back/login
                check_path: /back/login_check
                authenticator: app.security.user.authenticator
                default_target_path: /back
                #csrf_provider: security.csrf.token_manager
                failure_path: /back/login
                failure_forward: true
                failure_handler: user.security.auth_failure_handler

    access_control:
        - { path: ^(.*)/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back, roles: ROLE_BACK }

    # activate different ways to authenticate

    # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
    #http_basic: ~

    # https://symfony.com/doc/current/security/form_login_setup.html
    #form_login: ~
