authentication:
    type: rest
    resource: AppBundle\Controller\Api\AuthenticationController

delivery_type:
    type: rest
    resource: AppBundle\Controller\Api\DeliveryTypeController

product_type:
    type: rest
    resource: AppBundle\Controller\Api\ProductTypeController

user:
    type: rest
    resource: AppBundle\Controller\Api\UserController

role:
    type: rest
    resource: AppBundle\Controller\Api\RoleController

product:
    type: rest
    resource: AppBundle\Controller\Api\ProductController

stock:
    type: rest
    resource: AppBundle\Controller\Api\StockController

command:
    type: rest
    resource: AppBundle\Controller\Api\CommandController

cart:
    type: rest
    resource: AppBundle\Controller\Api\CartController